# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gzO9gAivCqwR9mBWYge6FU48MvHFoGbY
"""

from processamento_de_audio import aumentar_volume
from processamento_de_audio import diminuir_volume

aumentar_volume()
diminuir_volume()