# -*- coding: utf-8 -*-
"""Estudos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gzO9gAivCqwR9mBWYge6FU48MvHFoGbY
"""

def aumentar_volume():
    print('Aumentando volume')

def diminuir_volume():
    print('Diminuindo volume')